inherit_from: .rubocop_todo.yml


AllCops:
  DisplayCopNames: true
  Exclude:
    - 'remediations/**/*'
    - 'db/schema.rb' # we are generating this in each environment, so it introduces rubocop faults
