env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

sudo: false
language: ruby
cache: bundler

notifications:
  email: false

rvm:
  - 2.1
  - 1.9.3

script: bundle exec rake ci

matrix:
  allow_failures:
    - rvm: 2.1
