language: ruby
cache: bundler

notifications:
  email: false

before_install:
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
  - docker-compose up -d
  - docker-compose ps
  - yes | gem update --system

before_script:
  - echo "Waiting for services to start"
  - until curl --silent -XGET --fail -o /dev/null http://localhost:8983; do printf '.'; sleep 1; done
  - until curl --silent -XGET --fail -o /dev/null http://localhost:8984; do printf '.'; sleep 1; done
  - until curl --silent -XGET --fail -o /dev/null http://localhost:3001/status; do printf '.'; sleep 1; done
  - until curl --silent -XGET --fail -o /dev/null http://localhost:3002; do printf '.'; sleep 1; done
  - until curl --silent -XGET --fail -o /dev/null http://localhost:3003/status; do printf '.'; sleep 1; done
  - until curl --silent -XGET --fail -o /dev/null http://localhost:3004; do printf '.'; sleep 1; done
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - CC_TEST_REPORTER_ID=3cdbe95bc010f6d3a02b14a9e421d6e85e1626d9b105c372c303ed8585cc7e3f

rvm:
  - 2.7.1 # deployed
