notifications:
  email: false

sudo: required
services:
  - docker

before_install:
  - docker run -d -p 8984:8983 -v $PWD/solr_conf/conf/:/myconfig solr:7 solr-create -c hydrus-test -d /myconfig
  - docker run -d -p 8983:8080 suldlss/fcrepo:no-messaging-latest
  - docker run -d -p 127.0.0.1:3001:3000 suldlss/workflow-server:latest
  - docker run -d -p 127.0.0.1:3002:3000 suldlss/suri-rails:latest
  - docker ps -a

rvm:
  - 2.5.3 # deployed

script: bundle exec rake ci
