language: ruby
cache: bundler

notifications:
  email: false

before_install:
  - docker-compose up -d
  - docker-compose ps
  - yes | gem update --system

before_script:
  - echo "Waiting for Fcrepo to start"
  - until curl --silent -XGET --fail -o /dev/null http://localhost:8983; do printf '.'; sleep 1; done
  - until curl --silent -XGET --fail -o /dev/null http://localhost:8984; do printf '.'; sleep 1; done
  - until curl --silent -XGET --fail -o /dev/null http://localhost:3002; do printf '.'; sleep 1; done
  - until curl --silent -XGET --fail -o /dev/null http://localhost:3003; do printf '.'; sleep 1; done
  - until curl --silent -XGET --fail -o /dev/null http://localhost:3004; do printf '.'; sleep 1; done

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

rvm:
  - 2.5.3 # deployed
