language: ruby
cache: bundler

notifications:
  email: false

sudo: required

services:
  - docker

before_install:
  - docker-compose up -d
  - docker-compose ps
  - yes | gem update --system

before_script:
  - echo "Waiting for Fcrepo to start"
  - until curl --silent -XGET --fail -o /dev/null http://localhost:8983; do printf '.'; sleep 1; done
  - echo "Waiting for dor-services-app to start"
  - until curl --silent -XGET --fail -o /dev/null http://localhost:3003/v1/about; do printf '.'; sleep 1; done

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

rvm:
  - 2.5.3 # deployed
