version: '3.6'

services:
  solr:
    image: solr:7
    volumes:
      - ./solr_conf/conf/:/myconfig
    command: solr-create -c hydrus-test -d /myconfig
    ports:
      - 8984:8983

  fcrepo:
    image: suldlss/fcrepo:no-messaging-latest
    ports:
      - 8983:8080

  suri:
    image: suldlss/suri-rails:latest
    ports:
      - 3002:3000
    depends_on:
      - db
    environment:
      DATABASE_NAME: suri
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: sekret
      DATABASE_HOSTNAME: db
      DATABASE_PORT: 5432

  db:
    image: postgres:11
     # No ports shared externally, so that this doesn't conflict with the postgres
     # server that TravisCI starts up.
     # ports:
     #   - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=sekret
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis
    # No external ports enabled.
    # ports:
    # - 6379:6379
    volumes:
      - redis-data:/data

  workflow:
    image: suldlss/workflow-server:latest
    environment:
      - RAILS_LOG_TO_STDOUT=true
      - DATABASE_NAME=workflow-server
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=sekret
      - DATABASE_HOSTNAME=db
      - DATABASE_PORT=5432
      - SECRET_KEY_BASE="${SECRET_KEY_BASE}"
      - SETTINGS__DOR_SERVICES__URL=http://dor-services-app:3000
      # To generate the token: docker-compose run dor-services-app rake generate_token
      - SETTINGS__DOR_SERVICES__TOKEN=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJIeWRydXMtVGVzdCJ9.vfo6tMpMhoSqlNaIeW1N0CZKDHbNo_ABHHfpVmIZoHc
      - SETTINGS__ENABLE_STOMP=false
      - SETTINGS__REDIS__HOSTNAME=redis
    depends_on:
      - db
      - redis
    ports:
      - 3001:3000

  dor-services-app:
    image: suldlss/dor-services-app:latest
    ports:
      - 3003:3000
    environment:
      RAILS_LOG_TO_STDOUT: "true"
      DATABASE_NAME: dor-services-app
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: sekret
      DATABASE_HOSTNAME: db
      DATABASE_PORT: 5432
      REDIS_URL: redis://redis:6379/
      SETTINGS__SOLR__URL: http://solr:8983/solr/hydrus-test
      SETTINGS__FEDORA_URL: http://fedoraAdmin:fedoraAdmin@fcrepo:8080/fedora
      SETTINGS__SURI__URL: http://suri:3000
      SETTINGS__WORKFLOW_URL: http://workflow:3000
      SETTINGS__DOR_INDEXING__URL: http://dor-indexing-app:3000/dor
      SETTINGS__DOR__SERVICE_USER: dor-service-user
      SETTINGS__DOR__SERVICE_PASSWORD: dor-service-password
      RAILS_ENV: production
      SECRET_KEY_BASE: 769171f88c527d564fb65b4b7ef712d5ae9761a21e26a41cd7c88eb0af89c74f857b9be4089119f71cf806dfc8bf9d9d2f0df91c00b119c96f462b46ebf43b0f
    depends_on:
      - db
      - dor-indexing-app
      - fcrepo
      - solr
      - suri
      - workflow
      - redis

  dor-indexing-app:
    image: suldlss/dor-indexing-app:latest
    ports:
      - 3004:3000
    environment:
      SOLR_URL: http://solr:8983/solr/hydrus-test
      SETTINGS__SOLR__URL: http://solr:8983/solr/hydrus-test
      SETTINGS__DOR_SERVICES__URL: http://dor-services-app:3000
      # To generate the token: docker-compose run dor-services-app rake generate_token
      SETTINGS__DOR_SERVICES__TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJGb28ifQ.-BVfLTW9Q1_ZQEsGv4tuzGLs5rESN7LgdtEwUltnKv4
      SETTINGS__FEDORA_URL: http://fedoraAdmin:fedoraAdmin@fcrepo:8080/fedora
      SETTINGS__SOLRIZER_URL: http://solr:8983/solr/hydrus-test
      SETTINGS__WORKFLOW_URL: http://workflow:3000
    depends_on:
      - solr
      - fcrepo
      - workflow

volumes:
  postgres-data:
  redis-data:
