source "http://rubygems.org"
source "http://sulair-rails-dev.stanford.edu"

group :deployment do
  gem 'capistrano'
  gem 'capistrano-ext'
  gem 'rvm-capistrano'
  gem 'lyberteam-devel', '>=0.7.0'
  gem 'lyberteam-gems-devel', '>=0.8.1'
  gem 'net-ssh-kerberos'
end
