hydrus:
  show_test_banner: false
  exception_error_page:   true  # if true, a generic error page will be shown with no exception messages; if false, standard Rails exceptions are shown directly to the user
  exception_error_panel:  false
  host: 'hydrus-test.stanford.edu'
  exception_recipients: ''
  ur_apo_druid: 'druid:bb000bb0000'
  project_tag: 'Project : Hydrus'

purl:
  base_url: 'https://sul-purl-test.stanford.edu/'

workflow:
  url: 'https://workflow.example.com/workflow'

dor_services:
  url: 'http://localhost:3003'
  # To generate the token: docker-compose run dor-services-app rake generate_token
  token: 'eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJIeWRydXMtVGVzdCJ9.vfo6tMpMhoSqlNaIeW1N0CZKDHbNo_ABHHfpVmIZoHc'

stacks:
  document_cache_storage_root: ~
  document_cache_host: ~
  document_cache_user: ~
  local_workspace_root: ~
  storage_root: ~
  host: ~
  user: ~

solr:
  url: 'https://solr.example.com/solr/collection'

suri:
  url: 'http://localhost:3002'
  user: ~
  password: ~
  mint_ids: true

fedora:
  url: 'https://user:password@fedora.example.com:1000/fedora'

# ssl:
#   cert_file: "<%= Rails.root + 'config/certs/dlss-dev-test.crt' %>"
#   key_file: "<%= Rails.root + 'config/certs/dlss-dev-test.key' %>"
#   key_pass: ''

workflow:
  url: http://localhost:3001
  timeout: 120
