hydrus:
  initial_apo_title: 'Intial Hydrus APO title'
  app_workflow: 'hydrusAssemblyWF'
  show_test_banner: false
  exception_error_panel: false
  host: 'hydrus-test.stanford.edu'
  file_upload_path: 'uploads'
  exception_recipients: ''
  ur_apo_druid: 'druid:bb000bb0000'
  project_tag: 'Project : Hydrus'

purl:
  base_url: 'https://sul-purl-test.stanford.edu/'

dor_services:
  url: 'http://localhost:3003'
  # To generate the token: docker-compose run dor-services-app rake generate_token
  token: 'eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJIeWRydXMtVGVzdCJ9.vfo6tMpMhoSqlNaIeW1N0CZKDHbNo_ABHHfpVmIZoHc'

stacks:
  document_cache_host: ~
  local_stacks_root: ~
  local_workspace_root: ~

solr:
  url: 'https://solr.example.com/solr/collection'

suri:
  url: 'http://localhost:3002'
  user: ~
  password: ~
  mint_ids: true

fedora:
  url: 'https://user:password@fedora.example.com:1000/fedora'

# ssl:
#   cert_file: "<%= Rails.root + 'config/certs/dlss-dev-test.crt' %>"
#   key_file: "<%= Rails.root + 'config/certs/dlss-dev-test.key' %>"
#   key_pass: ''

workflow:
  url: http://localhost:3001
  timeout: 120
