hydrus:
  exception_error_panel: false
  exception_error_page: false
  host: localhost:3000
  start_assembly_wf: false

fedora:
  url: http://fedoraAdmin:fedoraAdmin@127.0.0.1:8983/fedora

suri:
  url: 'http://localhost:3002'
  user: ~
  password: ~
