hydrus:
  exception_error_panel: false
  host: localhost:3000
  start_assembly_wf: false

fedora:
  url: http://fedoraAdmin:fedoraAdmin@127.0.0.1:8983/fedora

purl:
  base_url: 'https://purl.stanford.edu/'

suri:
  url: 'http://localhost:3002'
  user: ~
  password: ~
  mint_ids: false

solr:
  url: http://localhost:8984/solr/hydrus-test
